### ISSUE TITLE
Erro ao clicar em "salvar" após criar novo tronco:  "A propriedade "Trunk.block_cid" não está definida."

### ISSUE THREAD

**Issue by viniciusbarretobr** [magnusbilling/mbilling#13]
Peguei a informação abaixo no log: /var/www/html/mbilling/protected/runtime/application.log

```
2023/09/27 14:57:28 [error] [exception.CException] CException: A propriedade "Trunk.block_cid" não está definida. in /var/www/ht>Stack trace:
#0 /var/www/html/mbilling/yii/framework/db/ar/CActiveRecord.php(162): CComponent->__set()
#1 /var/www/html/mbilling/yii/framework/base/CModel.php(472): CActiveRecord->__set()
#2 /var/www/html/mbilling/yii/framework/base/CComponent.php(152): CModel->setAttributes()
#3 /var/www/html/mbilling/yii/framework/db/ar/CActiveRecord.php(162): CComponent->__set()
#4 /var/www/html/mbilling/protected/components/BaseController.php(588): CActiveRecord->__set()
#5 /var/www/html/mbilling/yii/framework/web/actions/CInlineAction.php(49): BaseController->actionSave()
#6 /var/www/html/mbilling/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#7 /var/www/html/mbilling/yii/framework/web/CController.php(286): CController->runAction()
#8 /var/www/html/mbilling/yii/framework/web/CController.php(265): CController->runActionWithFilters()
#9 /var/www/html/mbilling/yii/framework/web/CWebApplication.php(282): CController->run()
#10 /var/www/html/mbilling/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#11 /var/www/html/mbilling/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()
#12 /var/www/html/mbilling/index.php(11): CApplication->run()
#13 {main}
REQUEST_URI=/mbilling/index.php/trunk/save?_dc=1695837447871
HTTP_REFERER=https://urlDoMagnusBilling/mbilling/

**Comment by viniciusbarretobr** [comment]
O problema deixou de ocorrer depois que atualizei o MagnusBilling.

Usei o script padrão para fazer este update: 
`/var/www/html/mbilling/protected/commands/update.sh`
